export type {
  Application,
  AnyComponentDefinition,
  ComponentContext,
  ComponentDefinition,
  ComponentSchema,
  CreateApplicationOptions,
  OptionDescriptor,
  OptionType,
  RefDescriptor,
  RefTag,
  ResolvedOption,
  ResolvedOptions,
  ResolvedRef,
  ResolvedRefs,
  StateMap,
  MethodsMap,
  MethodsFactory,
  WatchConfig
} from './entities'
